package com.ketan.QuizByAI.service;

import com.ketan.QuizByAI.exceptionHandler.AiLimitExceedException;
import com.ketan.QuizByAI.exceptionHandler.BadRequestException;
import com.ketan.QuizByAI.model.AiQuizRequestDTO;
import com.ketan.QuizByAI.model.Question;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor;
import org.springframework.ai.chat.client.advisor.StructuredOutputValidationAdvisor;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Random;

@Service
public class QuizByAiService {

    private static final Logger log = LoggerFactory.getLogger(QuizByAiService.class);
    private final ChatClient chatClient;

    public QuizByAiService(ChatClient.Builder builder) {
        this.chatClient = builder
                .defaultSystem(defaultSystemPrompt())
                .build();
    }

    public List<Question> generateQuestion(AiQuizRequestDTO dto) {

        if(validateTopic(dto.getTopic())) {
            throw new BadRequestException("Inappropriate Quiz topic!");
        }

        //Structures the response received from ai, if there is some mistake in response is request back to ai with error message
        ParameterizedTypeReference<List<Question>> typeReference = new ParameterizedTypeReference<>() {};
        StructuredOutputValidationAdvisor validationAdvisor = StructuredOutputValidationAdvisor.builder()
                .outputType(typeReference)
                .maxRepeatAttempts(3) // It will try to fix the JSON 3 times before failing
                .build();

        List<Question> questions = null;

        try {
            questions = this.chatClient.prompt()
                    .user(getPrompt(dto))
                    .advisors(validationAdvisor) //logs request and response automatically and validate response
                    .call()
                    .entity(new ParameterizedTypeReference<List<Question>>() {}); //In simple terms: It creates a "Super Type Token" that preserves the specific generic type (List<Question>) at runtime, preventing Java from losing that information due to Type Erasure.

        } catch (Exception e) {
            String errorMsg = e.getMessage();

            // 1. Handle Daily Quota
            if (errorMsg.contains("quota") || errorMsg.contains("insufficient_quota") || errorMsg.contains("billing")) {
                log.error("Daily/Billing Quota reached for Groq API!");
                throw new AiLimitExceedException("Our AI Guruji has reached his daily limit. Please come back tomorrow!");
            }

            // 2. Handle TPM/RPM
            if (errorMsg.contains("429") || errorMsg.contains("rate limit") || errorMsg.contains("tpm")) {
                log.error("TPM/RPM Limit exceeded for topic: {}", dto.getTopic());
                throw new AiLimitExceedException("Too many requests for Guruji to handle! Please wait for 60 seconds before trying again.");
            }

            // 3. other errors
            log.error("Unexpected AI Error: {}", e.getMessage());
            throw new AiLimitExceedException("Guruji is having some trouble. Try again in a few minutes.");
        }

        log.info("Questions generated by AI Guruji!");
        return questions;
    }

    public boolean validateTopic(String topic) {
        List<String> forbiddenTerms = List.of(
                // 1. Profanity & Slurs
                "fuck", "shit", "bitch", "asshole", "dick", "pussy", "nigger", "faggot",

                // 2. Violence & Harm
                "violence", "murder", "terrorism", "bomb", "suicide", "torture", "rape", "war crimes", "genocide",

                // 3. Illegal Activities
                "illegal", "drugs", "cocaine", "heroin", "meth", "theft", "hacking", "fraud", "scam",

                // 4. Explicit/Adult Content
                "explicit", "porn", "erotic", "nudity", "hentai", "xxx",

                // 5. Sensitive/Divisive Topics (Optional but recommended for schools)
                "racism", "hate speech", "extremism", "white supremacy", "nazism"
        );

        if(topic == null || topic.isBlank())
            return false;

        if (topic.matches(".*[bcdfghjklmnpqrstvwxyz]{5,}.*")) {
            log.warn("Gibberish detected: {}", topic);
            return true;
        }

        return forbiddenTerms.stream().anyMatch(topic.toLowerCase()::contains);
    }

    private String defaultSystemPrompt() {
        return "You are an Elite Competitive Exam Designer (specializing in CAT, GMAT, and JEE Advanced). " +
                "Your goal is to challenge the smartest students. " +
                "STRICT RULE: Never generate single-step questions. " +
                "Generate unique quiz questions in strict JSON format. Output ONLY a raw JSON array. " +
                "STRUCTURE: Use qno (int), quizId (1), question (string), opt1, opt2, opt3, opt4. " +
                "CRITICAL: correctOpt MUST contain the EXACT TEXT VALUE of the correct option, not the key name.";
    }

    private String getPrompt(AiQuizRequestDTO dto) {
        int randomSeed = new Random().nextInt(10000);
        String diff = dto.getDifficulty().toLowerCase();

        return String.format(
                """
                        Request ID: #%d. Role: Master Instructional Designer & Assessment Expert.
                        Task: Generate exactly %d unique questions for the specific topic '%s' in %s language.
                        
                        --- 0. DOMAIN ADAPTATION & TOPIC ANCHOR (CRITICAL) ---
                        - Analyze the topic '%s' carefully. 
                        - STRICT BOUNDARY: Every question must exclusively test '%s'. Do NOT drift into related but different sub-topics (e.g., if the topic is 'Articles', do not include 'Relative Pronouns' like who/which).
                        - PEDAGOGICAL MATCH: If the topic is grammar/language, use 'Fill-in-the-blanks' or 'Sentence Completion'. If technical, use code snippets or logic scenarios.
                        
                        --- 1. DYNAMIC DIFFICULTY SCALING (%s) ---
                        Calibrate the cognitive demand strictly to this level:
                        - EASY: Focus on 'Identify' & 'Remember'. Direct facts and clear examples.
                        - MODERATE: Focus on 'Understand' & 'Apply'. Predict outcomes or apply a rule to a standard scenario.
                        - HARD: Focus on 'Analyze' & 'Evaluate'. Multi-layered systems, edge cases, exceptions to rules, or identifying subtle errors.
                        
                        --- 2. STRUCTURAL VARIETY (ANTI-REPETITION) ---
                        Do NOT repeat the same sentence structure. Rotate through these 4 frames:
                        A. THE SCENARIO: Provide a context/story and ask for the implication.
                        B. THE REVERSE: Give the result/output and ask for the specific cause/input.
                        C. THE COMPARISON: Contrast two sub-elements of the topic and identify the differentiator.
                        D. THE DIRECT: A sophisticated inquiry into a specific mechanism or rule.
                        
                        --- 3. LANGUAGE & SCRIPT PRECISION (STRICT GUARDRAILS) ---
                        - STRICT NATIVE SCRIPT: Use only %s Devnagari script.
                        - NO TRANSLITERATION: Do NOT include English words in brackets (e.g., No 'Sanskutī (Culture)').
                        - NO CODE-SWITCHING: Do not mix English grammar or phonetics into %s sentences.
                        - PURE TERMINOLOGY: Use the standard academic terms of the target language.
                        
                        --- 4. CONCISE OPTION RULE (MANDATORY) ---
                        - COMPLEX STEM: Put all necessary context and complexity in the 'question' field.
                        - SHORT OPTIONS: Every 'opt' must be 1-7 words maximum.
                        - CORRECT OPTION: The 'correctOpt' field must contain the EXACT TEXT of the correct answer, NEVER the key name (e.g., never return 'opt2').
                        - PLAUSIBILITY: Distractors must be 'near-misses'—logically tempting but technically incorrect.
                        
                        --- 5. SUBJECT INTEGRITY ---
                        - No math word problems for non-math topics.
                        - Use technical terminology appropriate for the %s difficulty level.
                        
                        Output strictly raw JSON array. No preamble.""",
                randomSeed,         // 1. #%d
                dto.getCount(),     // 2. %d
                dto.getTopic(),     // 3. topic '%s'
                dto.getLanguage(),  // 4. %s language
                dto.getTopic(),     // 5. Analyze '%s'
                dto.getTopic(),     // 6. test '%s'
                diff.toUpperCase(), // 7. scaling (%s)
                dto.getLanguage(),  // 8. %s Devnagari script
                dto.getLanguage(),  // 9. %s sentences
                diff.toUpperCase()  // 10. %s difficulty level
        );
    }

}
